name: ielts_practice_mobile
description: Ielts Practice
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  bloc: ^8.1.0
  cached_network_image: ^3.2.2
  dio: ^4.0.6
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.14
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  image_picker: ^0.8.6
  intl: ^0.17.0
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15
  tab_indicator_styler: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.5.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - development.env
    - production.env
    - assets/
